### ISSUE TITLE
theme_unhcr_map

### ISSUE THREAD

**Issue by zanmat** [unhcr-dataviz/unhcrthemes#34]
Is theme_unhcr_map still an available function in unhcrthemes? The [examples on UNHCR DataViz](https://dataviz.unhcr.org/tools/r/r_choropleth_map.html) still use it but it now returns an error:
<html>
<body>

Error: 'theme_unhcr_map' is not an exported object from 'namespace:unhcrthemes'
--
 
  |  
 

<br class="Apple-interchange-newline">
</body>
</html>

This worked fine before, so it might be a recent change?

**Comment by vidonne** [comment]
The function `theme_unhcr_map` doesn't exist anymore. It has been replaced by the `theme_unhcr(void = TRUE)` approach, you can find an example in action in our [30DayMapChallenge2023](https://github.com/unhcr-dataviz/30DayMapChallenge2023/tree/main/01_points) repo.

You're right we need to update the UNHCR Dataviz Platform but we are working on a new backend for the platform so it will most likely come together with the migration.
